### PR TITLE
Feature/store conversion rates on chain.

### PR DESCRIPTION
**Pull request by Allen-Muhani**

### CODE REVIEW

**Review by dmutinda — APPROVED** [review]

**Comment by steffenkrogmann** [comment]
@Kukuza/developers don't merge yet. 
What is the reason why we need to store conversion rates on chain now?

**Comment by Allen-Muhani** [comment]
So that the front end can do conversions of any values within the transactions without calling the currency conversion  APIs.
@steffenkrogmann

**Comment by steffenkrogmann** [comment]
@Allen-Muhani  and why do you save the conversion rate on-chain and not the actual amounts?

Because you don't need the rate to calculate new amounts, right?

**Comment by Allen-Muhani** [comment]
It restores the responsibility of fiat conversion for whatever field within the transaction to the front end. 
This eliminates the need of storing any new field the front end would want to display in fiat.
in case of a new field that has the currency values that are needed by the FE in local fiat. The smart contract eliminates itself from the conversion saga. 

i.e All the amounts values are stored on-chain and the front end has whatever it needs to convert the values to fiat and display them.
@steffenkrogmann

**Comment by steffenkrogmann** [comment]
@Allen-Muhani got it.

so more flexibility, looking into the future, in case other amounts would have to be displayed

**Pull request merged**
